### ISSUE TITLE
Потрібно зменшити розмір файлів картинок

### ISSUE THREAD

**Issue by TanuhaUA** [YuraSadilenko/bouncy#31]
Є невиправдано великі за розміром картинки. Якщо це фонова велика картинка - то вона ще може бути в районі 500Кб. А от невеликі зображення часто можуть поміститись в 30-40Кб, ну або 100.. У вас є всі картинки займають близько 6Мб.. Особливо невиправдано великий Фьюрі :) 
Передивіться, будь ласк, всі зображення:) 
Є онлайн-ресурси для оптимізації. Або можна в фотошопі.

**Comment by YuraSadilenko** [comment]
done
