### ISSUE TITLE
Висота блоку фіксована і не залежить від контенту. При великому тексті ламається

### ISSUE THREAD

**Issue by TanuhaUA** [YuraSadilenko/bouncy#39]
https://github.com/YuraSadilenko/bouncy/blob/8de9ef5c0274d591f968cb4045544cc3ae9a6a16/src/index.html#L517

<img width="771" alt="default" src="https://user-images.githubusercontent.com/12620993/49756791-7960a800-fcc3-11e8-9828-1b0948853241.png">

**Comment by TanuhaUA** [comment]
В блоці slider-box-comment та ж сама проблема

**Comment by TanuhaUA** [comment]
І блок .subscribe теж...

**Comment by YuraSadilenko** [comment]
done
